//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC.DefaultPlugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC.Core.DefaultPlugins.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cw==.
        /// </summary>
        internal static string AllSeeingEye {
            get {
                return ResourceManager.GetString("AllSeeingEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //9nZXRJbmZv.
        /// </summary>
        internal static string Doom3 {
            get {
                return ResourceManager.GetString("Doom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XGJhc2ljXA==.
        /// </summary>
        internal static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v0AQ09SWf//AA==.
        /// </summary>
        internal static string GS2 {
            get {
                return ResourceManager.GetString("GS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v0ADK49AP///wE=.
        /// </summary>
        internal static string GS3 {
            get {
                return ResourceManager.GetString("GS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /v0JAQIDBA==.
        /// </summary>
        internal static string GS4 {
            get {
                return ResourceManager.GetString("GS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /////1RTb3VyY2UgRW5naW5lIFF1ZXJ5AA==.
        /// </summary>
        internal static string HalfLife {
            get {
                return ResourceManager.GetString("HalfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerCheckerv4 is licensed under the terms of the GNU General Public License v2.
        ///
        ///                    GNU GENERAL PUBLIC LICENSE
        ///                       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The licenses for most software are designed t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /////3N0YXR1cw==.
        /// </summary>
        internal static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /////2dldHN0YXR1cw==.
        /// </summary>
        internal static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UkVQT1JU.
        /// </summary>
        internal static string RavenShield {
            get {
                return ResourceManager.GetString("RavenShield", resourceCulture);
            }
        }
    }
}
